#!/usr/bin/with-contenv bash

file_env() {
    local suffix="_FILE"
	local var="${1%$suffix}"
	local fileVar="$1"
	local def="${2:-}"
	if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then
		echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
		exit 1
	fi
	local val="$def"
	if [ "${!var:-}" ]; then
		val="${!var}"
	elif [ "${!fileVar:-}" ]; then
		val="$(< "${!fileVar}")"
	fi
	export "$var"="$val"
	echo "Expanding secret at ${!fileVar} into '$var'"
	unset "$fileVar"
}

# Get all vars ending in '_FILE' and fetch their corresponding secret
for var in $(env | awk -F "=" '{print $1}' | grep ".*_FILE$")
do
	file_env $var
done